apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: backend
spec:
  containers:
  - name: backend
    image: phsinghka/proshop-backend:latest
    ports:
      - containerPort: 5000
