apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  containers:
  - name: frontend
    image: phsinghka/proshop-frontend:latest
    ports:
      - containerPort: 5000
