apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "mongoadmin"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "secret"
