version: '3'
services:
  backend: 
    image: phsinghka/proshop-backend:v1
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ENV PORT=5000
      - ENV MONGO_URI=mongodb://mongoadmin:secret@mongo:27017
      - ENV JWT_SECRET=abc123
    depends_on:
      - mongo

  frontend: 
    image: phsinghka/proshop-frontend:v1
    container_name: frontend
    depends_on:
      - backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  

